owner: drawbeat
repo: upptime

sites:
  # - name: drawbeat.com
  #   url: http://drawbeat.com
  # - name: admin.drawbeat.com
  #   url: http://admin.drawbeat.com
  # - name: api.drawbeat.com
  #   url: https://api.drawbeat.com/v1/auth/me

status-website:
  cname: upptime.drawbeat.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for Drawbeat
